name: provider
description: A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 4.3.2+2
homepage: https://github.com/rrousselGit/provider
authors:
  - Remi Rousselet <darky12s@gmail.com>
  - Flutter Team <flutter-dev@googlegroups.com>

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">= 1.16.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.0
  nested: ^0.0.5-nullsafety.1

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
